services:
- type: web
  name: finance-tracker-api
  runtime: docker
  repo: https://github.com/Zerefez/FinanceTracker-Backend
  region: oregon
  plan: free
  branch: main
  dockerfilePath: ./FinanceTracker/Dockerfile
  numInstances: 1
  healthCheckPath: /health
  envVars:
  - key: ASPNETCORE_ENVIRONMENT
    value: Production
  - key: ConnectionStrings__DefaultConnection
    value: "Server=tcp:financetracker11-server.database.windows.net,1433;Initial Catalog=FinanceTrackerDB;Persist Security Info=False;User ID=RAAA;Password=RUNRUN123!;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
  - key: JWT__Issuer
    value: "MyBGList"
  - key: JWT__Audience
    value: "MyBGList"
  - key: JWT__SigningKey
    value: "Khizer8!Khizer8!Khizer8!Khizer8!Khizer8!"
