name: Trigger auto deployment for financetraacker

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/financetraacker-AutoDeployTrigger-897bfd3e-810e-4334-98de-fa55200adaea.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.FINANCETRAACKER_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.FINANCETRAACKER_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.FINANCETRAACKER_AZURE_SUBSCRIPTION_ID }}

      - name: Register required providers
        run: |
          az provider register -n Microsoft.App --wait
          az provider register -n Microsoft.OperationalInsights --wait

      - name: Create Container App Environment
        run: |
          az containerapp env create \
            --name financetraacker-env \
            --resource-group financetracker \
            --location westus2 \
            --logs-workspace-id ${{ secrets.LOG_ANALYTICS_WORKSPACE_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/FinanceTracker
          dockerfilePath: Dockerfile
          registryUrl: docker.io
          registryUsername: ${{ secrets.FINANCETRAACKER_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.FINANCETRAACKER_REGISTRY_PASSWORD }}
          containerAppName: financetraacker
          resourceGroup: financetracker
          containerAppEnvironment: financetraacker-env
          imageToBuild: RAAA/financetraacker:${{ github.sha }}
          targetPort: 8080
          ingress: external
          location: westus2


